---
- name: Install kubectl
  hosts: localhost
  user: ubuntu
  become: yes

  tasks:
    - name: 1. Update apt cache
      apt:
        update_cache: yes

    - name: 2. Download Kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: 3. Verify kubectl installation
      shell: kubectl version --client
      register: kubectl_version

    - name: 4. Display kubectl installation
      debug:
        msg: "{{ kubectl_version.stdout }}"
