name: CD pipeline 
on: 
 workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs: 
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Start Minikube
        run: |
          minikube start --driver=none
          minikube status

      - name: Set Docker env for Minikube
        run: eval $(minikube docker-env)
        
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:latest
        
      - name: Pull Docker image 
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:latest 

      - name: Apply Kubernetes deployment
        run: kubectl apply -f k8s/deployment.yaml

      - name: Apply Kubernetes service
        run: kubectl apply -f k8s/service.yaml
      
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/weather-ml-app weather-ml-app=${{ secrets.DOCKERHUB_USERNAME }}
          kubectl rollout status deployment/weather-ml-app
