name: CD pipeline 
on: 
 workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs: 
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v1

      - name: Download image version artifact
        uses: actions/download-artifact@v4
        with:
          name: image-version
          path: .

      - name: Read image version into environment variable
        run: |
          IMAGE_VERSION=$(cat image-version.txt)
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV

      - name: Apply Kubernetes Deployment & Service
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/weather-ml-app \
            weather-ml-app=afell300/weather-ml-app:${{ env.IMAGE_VERSION }}
          kubectl rollout status deployment/weather-ml-app
