name: CI pipeline

on:
  push:
    branches:
      - main
      - bugfix
  pull_request:
    branches: -main

env:
  IMAGE_VERSION: v2

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.3

      # Install dependencies
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install Flask gunicorn

      - name: Run smoke test
        run: |
          python -m unittest tests/smoke_test.py

      - name: Run unit test
        run: |
          python -m unittest tests/unit_test.py

      - name: Run integration test
        run: |
          python -m unittest tests/integration_test.py

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/weather-ml-app:${{ env.IMAGE_VERSION }}

      - name: Save image version to artifact
        run: echo "${{ env.IMAGE_VERSION }}" > image_version.txt
      - uses: actions/upload-artifact@v3
        with:
          name: image-version
          path: image_version.txt
